name: Simple CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Stage
        run: echo "Build stage executed"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test Stage
        run: echo "Test stage executed"
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy Stage
        run: echo "Deploy stage executed"

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Notify Stage
        run: echo "Notify stage executed"

